name: rentsoed_app
description: "Aplikasi Rental Motor Rentsoed"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0 

dependencies:
  flutter:
    sdk: flutter
  
  json_annotation: ^4.9.0 

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10
  gap: ^3.0.1
  cached_network_image: ^3.4.1
  
  intl: ^0.19.0
  provider: ^6.1.2
  url_launcher: ^6.3.0
  flutter_rating_bar: ^4.0.1
  
  supabase_flutter: ^2.8.3
  image_picker: ^1.1.2
  google_sign_in: ^6.1.6
  flutter_local_notifications: ^17.0.0
  
  # --- FIX KONFLIK: Versi postgrest dinaikkan ke ^2.5.0 ---
  # Ini mengatasi error karena versi lama postgrest bentrok dengan dependensi supabase
  postgrest: ^2.5.0 

dev_dependencies:
  build_runner: ^2.4.7 
  json_serializable: ^6.7.1 

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/